microservice:
  replicaCount: 1

  image:
    repository: ghcr.io/victordomoto/app-hello-php  
    tag: "1.0.0"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  ingress:
    enabled: true
    className: "haproxy"
    host: hello-php.homelab.local    

  env:
    APP_ENV: dev

  resources: {}
