apiVersion: v2
name: dev-hello-php
description: Release chart for hello-php app on homelab
type: application
version: 1.0.0

dependencies:
  - name: microservice
    version: "1.0.0"
    repository: "https://github.com/victordomoto/php-workload-chart/charts/php"
